server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.elevenchu.springcloud.service.PaymentFeignService: debug
